declare module "*.module.css"
declare module "*.jpg"
declare module "*.svg"
declare module "@sanity/block-content-to-react"
declare module "@atoms/*"
declare module "@components/*"
declare module "@assets/*"
